test:
  type: remote
  path: cdn.140kit.com/files
  user: gonkclub
  host: 208.97.135.171

development:
  type: local
  path: results #This will always be relative to project root.

production:
  type: remote
  path: results
  user: some_user_on_remote_machine
  host: some.domain.name  

  