group :core do
  source 'http://rubygems.org'
  source 'http://gems.github.com'
  gem 'dm-aggregates'
  gem 'dm-chunked_query'
  gem 'dm-core'
  gem 'dm-migrations'
  gem 'dm-mysql-adapter'
  gem 'dm-sqlite-adapter'
  gem 'dm-sweatshop'
  gem 'dm-types'
  gem 'dm-zone-types'  
  gem 'dm-validations'
  gem 'eventmachine', '1.0.0.beta.4'
  gem 'em-http-request', :require => 'em-http'
  gem 'geokit'
  gem 'htmlentities'
  gem 'jeweler'#, '1.5.2'
  gem 'json'
  gem 'mechanize'
  gem 'mocha'
  gem 'nokogiri'
  gem 'ntp'
  gem 'oauth'
  gem 'mysql2'
  gem 'spicycode-rcov'
  gem 'RedCloth'
  gem 'rdebug'
  gem 'rspec', '1.3.1'
  gem 'useful_class_extensions'
  gem 'tweetstream', '1.1.2'
  gem 'twitter'
  gem 'unicode'
  gem 'yajl-ruby'
end

group :raw_csv do
  gem 'fastercsv'
end

group :compact_language_detection do
  gem 'cld'
end

group :semantic_analyzer do
  gem 'josephwilk-rsemantic'
  gem 'stemmer'
end

group :fast_semantic_analyzer do
  gem 'tf_idf'
end