#!/usr/bin/env rake
# Add your own tasks in files placed in lib/tasks ending in .rake,
# for example lib/tasks/capistrano.rake, and they will automatically be available to Rake.

# ALLOWED_RAKES = %w{
#   db:schema:dump
#   routes
#   assets:precompile
# }
# 
# unless ARGV.length == 1 && ALLOWED_RAKES.include?(ARGV.first)
#   puts "You might be trying to do something bad. Do you really want to do this? (yes/no)"
#   # if STDIN.gets.strip.downcase != 'yes'
#     # puts "Exiting..."
#     # exit
#   # end
# end

require File.expand_path('../config/application', __FILE__)

WWW140kit::Application.load_tasks
